### ISSUE TITLE
[Discussion] Study Publications and Contacts are not written fo xlsx

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ARCtrl#160] opened 2023-08-04 20:05 UTC
We ensured that they were correctly added to the model. ARCtrl.ISA.Spreadsheet does **not** correctly parse this into a FsWorkbook. There we verified the information to be missing.

I am pretty sure the ARCtrl.ISA.Spreadsheet/InvestigationFile/Study=> `Studies.toSparseTable` function does not include both `Publications` and `Contacts`. This is a critical error for Arcitect.

**Comment by HLWeil** [comment] 2023-08-05 06:14
Not a bug. This is by design. The amount of duplicate information between the study file and Investigation file is a pain to handle.

**Comment by HLWeil** [comment] 2023-08-05 06:14
Was a bad Idea to include all this information in the study file to begin with.

**Comment by Freymaurer** [comment] 2023-08-05 07:37
When i contacted you about what fields are not needed for our arctypes. Why did we keep those?

**Comment by HLWeil** [comment] 2023-08-05 09:25
They are needed. Just not part of the study file. They are part of the investigation file

**Comment by HLWeil** [comment] 2023-08-05 09:27
That's what I meant with duplicate information. Keeping investigation and study file synchronous

**Comment by Freymaurer** [comment] 2023-08-05 09:49
> They are needed. Just not part of the study file. They are part of the investigation file

I get that, but why does ArcStudy need publications and contacts?

**Comment by HLWeil** [comment] 2023-08-05 12:10
Well it is a property of the study. But stored in the investigation file.

**Comment by HLWeil** [comment] 2023-08-05 12:13
The study object of the investigation file and the study object of the study file are complmentary and need to be merged by the "SetISAFromContracts" method.

**Comment by Freymaurer** [comment] 2023-08-05 15:23
I think I cannot follow. Can you explain to me where the contacts from ArcStudy are used?

**Comment by HLWeil** [comment] 2023-08-05 20:38
They are read from and written to the Investigation file.  
That's part of the isa specification.

It's up to the user what he uses them for.

**Comment by Freymaurer** [comment] 2023-08-07 08:54
- Study/Assay Contacts should be written to respective xlsx. files
- add sync contacts function on investigation level to also pull lower level contacts/performers to investigation lvl.
- write=read

**Comment by HLWeil** [comment] 2023-08-09 07:10
`Study/Assay Contacts should be written to respective xlsx. files`
This would imply that we should drop this info from the investigation file altogether. It would be exactly duplicated information.
`add sync contacts function on investigation level to also pull lower level contacts/performers to investigation lvl.`
Depends on how you interpret it. A person being responsible for one study does not necessarily mean that this person is also responsible for the full investigation.
`write=read`
Agreed, but where is this not the case in this specific scenario?

**Comment by Freymaurer** [comment] 2023-08-09 07:54
I talked with Timo and Dominik about this and the current intent is to keep performers on assays/studies and investigation. People can be in an assay but not in the investigation and reverse.

User friendly handling of persons must be done by the UIs. Example. Autocomplete full person by suggestion.

**Comment by HLWeil** [comment] 2023-08-11 21:37
closing in favor of #167

**Closed by HLWeil** 2023-08-11 21:37 UTC
Labels: bug
